### ISSUE TITLE
@ExperimentFunction missing methods in experiment_tutorial.ipynb

### ISSUE THREAD

**Issue by jlhsage** [QUVA-Lab/artemis#127]
In the Jupyter file experiment_tutorial.ipynb there is a cell containing the following statements:

demo_drunkards_walk.clear_records(include_children=True)
demo_drunkards_walk.run_all()

Both statements give the error that they do not have methods 'clear_records' or 'run_all', respectively.  The function 'demo_drunkards_walk' is decorated in the previous cell by ExperimentFunction.

**Comment by petered** [comment]
Thanks for catching that.  Fixed in https://github.com/QUVA-Lab/artemis/pull/128 .  Tutorial is updated: https://rawgit.com/petered/data/master/gists/experiment_tutorial.html

**Comment by petered** [comment]
Great to hear.  As it happens, I've just been using it for parameter search.  There're really 2 ways to do it:

1) Make a bunch of variants

2) Do the search inside the experiment - here it might be useful to use yield instead of return, which saves a result on every yield instead of just at the end, so you can manually terminate the experiment and still get a result.  

Re: the windows thing, feel free to submit a pull request
